City.create(name: "Mumbai")
City.create(name: "Navi Mumbai")
City.create(name: "Thane")

Pincode.create(:city => "Mumbai",:name =>"Mumbai G P O",:pin_number=>"400001")
Pincode.create(:city => "Mumbai",:name =>"Kalbadevi",:pin_number=>"400002")
Pincode.create(:city => "Mumbai",:name =>"Mandvi",:pin_number=>"400003")
Pincode.create(:city => "Mumbai",:name =>"Masjid Bunder",:pin_number=>"400003")
Pincode.create(:city => "Mumbai",:name =>"Girgaon",:pin_number=>"400004")
Pincode.create(:city => "Mumbai",:name =>"Colaba",:pin_number=>"400005")
Pincode.create(:city => "Mumbai",:name =>"Malabar Hill",:pin_number=>"400006")
Pincode.create(:city => "Mumbai",:name =>"Grant Road",:pin_number=>"400007")
Pincode.create(:city => "Mumbai",:name =>"Byculla",:pin_number=>"400008")
Pincode.create(:city => "Mumbai",:name =>"Mumbai Central",:pin_number=>"400008")
Pincode.create(:city => "Mumbai",:name =>"Chinch Bunder",:pin_number=>"400009")
Pincode.create(:city => "Mumbai",:name =>"Masjid Bunder",:pin_number=>"400009")
Pincode.create(:city => "Mumbai",:name =>"Mazgaon",:pin_number=>"400010")
Pincode.create(:city => "Mumbai",:name =>"Jacob Circle",:pin_number=>"400011")
Pincode.create(:city => "Mumbai",:name =>"Mahalaxmi",:pin_number=>"400011")
Pincode.create(:city => "Mumbai",:name =>"Currey Road",:pin_number=>"400012")
Pincode.create(:city => "Mumbai",:name =>"Parel",:pin_number=>"400012")
Pincode.create(:city => "Mumbai",:name =>"Delisle Road",:pin_number=>"400013")
Pincode.create(:city => "Mumbai",:name =>"Lower Parel",:pin_number=>"400013")
Pincode.create(:city => "Mumbai",:name =>"Dadar (W)",:pin_number=>"400014")
Pincode.create(:city => "Mumbai",:name =>"Sewree",:pin_number=>"400015")
Pincode.create(:city => "Mumbai",:name =>"Mahim",:pin_number=>"400016")
Pincode.create(:city => "Mumbai",:name =>"Dharavi",:pin_number=>"400017")
Pincode.create(:city => "Mumbai",:name =>"Worli",:pin_number=>"400018")
Pincode.create(:city => "Mumbai",:name =>"Matunga",:pin_number=>"400019")
Pincode.create(:city => "Mumbai",:name =>"Marine Lines",:pin_number=>"400020")
Pincode.create(:city => "Mumbai",:name =>"Nariman Point",:pin_number=>"400021")
Pincode.create(:city => "Mumbai",:name =>"Chunabhatti",:pin_number=>"400022")
Pincode.create(:city => "Mumbai",:name =>"Kurla (E)",:pin_number=>"400022")
Pincode.create(:city => "Mumbai",:name =>"Sion",:pin_number=>"400022")
Pincode.create(:city => "Mumbai",:name =>"Hutatma Chowk",:pin_number=>"400023")
Pincode.create(:city => "Mumbai",:name =>"Nehru Nagar Kurla (E)",:pin_number=>"400024")
Pincode.create(:city => "Mumbai",:name =>"Prabhadevi",:pin_number=>"400025")
Pincode.create(:city => "Mumbai",:name =>"Cumballa Hill",:pin_number=>"400026")
Pincode.create(:city => "Mumbai",:name =>"Byculla (E)",:pin_number=>"400027")
Pincode.create(:city => "Mumbai",:name =>"Bhavani Shankar Road Dadar (E)",:pin_number=>"400028")
Pincode.create(:city => "Mumbai",:name =>"Dadar (E)",:pin_number=>"400028")
Pincode.create(:city => "Mumbai",:name =>"Kalina / Santacruz P&T Colony",:pin_number=>"400029")
Pincode.create(:city => "Mumbai",:name =>"Wadala",:pin_number=>"400031")
Pincode.create(:city => "Mumbai",:name =>"Mantralaya",:pin_number=>"400032")
Pincode.create(:city => "Mumbai",:name =>"Cotton Green",:pin_number=>"400033")
Pincode.create(:city => "Mumbai",:name =>"Tank Road",:pin_number=>"400033")
Pincode.create(:city => "Mumbai",:name =>"Haji Ali",:pin_number=>"400034")
Pincode.create(:city => "Mumbai",:name =>"Mahalaxmi",:pin_number=>"400034")
Pincode.create(:city => "Mumbai",:name =>"Tardeo",:pin_number=>"400034")
Pincode.create(:city => "Mumbai",:name =>"Walkeshwar",:pin_number=>"400035")
Pincode.create(:city => "Mumbai",:name =>"Cumballa Hill",:pin_number=>"400036")
Pincode.create(:city => "Mumbai",:name =>"Antop Hill",:pin_number=>"400037")
Pincode.create(:city => "Mumbai",:name =>"Ballard Estate",:pin_number=>"400038")
Pincode.create(:city => "Mumbai",:name =>"Cuffe Parade",:pin_number=>"400039")
Pincode.create(:city => "Mumbai",:name =>"Poonam Ngr Jogeshwari (E)",:pin_number=>"400041")
Pincode.create(:city => "Mumbai",:name =>"Bhandup (E)",:pin_number=>"400042")
Pincode.create(:city => "Mumbai",:name =>"Shivaji Nagar Govandi (W)",:pin_number=>"400043")
Pincode.create(:city => "Mumbai",:name =>"Kurla (E)",:pin_number=>"400043")
Pincode.create(:city => "Mumbai",:name =>"Juhu",:pin_number=>"400049")
Pincode.create(:city => "Mumbai",:name =>"Santacruz (W)",:pin_number=>"400049")
Pincode.create(:city => "Mumbai",:name =>"Bandra (W)",:pin_number=>"400050")
Pincode.create(:city => "Mumbai",:name =>"Bandra (E)",:pin_number=>"400051")
Pincode.create(:city => "Mumbai",:name =>"Khar (W)",:pin_number=>"400052")
Pincode.create(:city => "Mumbai",:name =>"Andheri (W)",:pin_number=>"400053")
Pincode.create(:city => "Mumbai",:name =>"Santacruz (West)",:pin_number=>"400054")
Pincode.create(:city => "Mumbai",:name =>"Santacruz (E)",:pin_number=>"400055")
Pincode.create(:city => "Mumbai",:name =>"Vile Parle (W)",:pin_number=>"400056")
Pincode.create(:city => "Mumbai",:name =>"Vile Parle (E)",:pin_number=>"400057")
Pincode.create(:city => "Mumbai",:name =>"Andheri (West)",:pin_number=>"400058")
Pincode.create(:city => "Mumbai",:name =>"Andheri (E) J B Nagar",:pin_number=>"400059")
Pincode.create(:city => "Mumbai",:name =>"Jogeshwari (East)",:pin_number=>"400060")
Pincode.create(:city => "Mumbai",:name =>"Goregaon (E)",:pin_number=>"400061")
Pincode.create(:city => "Mumbai",:name =>"Vesava (Versova)",:pin_number=>"400061")
Pincode.create(:city => "Mumbai",:name =>"Goregaon (West)",:pin_number=>"400062")
Pincode.create(:city => "Mumbai",:name =>"Goregaon (E)",:pin_number=>"400063")
Pincode.create(:city => "Mumbai",:name =>"Malad (W)",:pin_number=>"400064")
Pincode.create(:city => "Mumbai",:name =>"Aarey Milk Colony",:pin_number=>"400065")
Pincode.create(:city => "Mumbai",:name =>"Borivali (E)",:pin_number=>"400066")
Pincode.create(:city => "Mumbai",:name =>"Kandivali (W)",:pin_number=>"400067")
Pincode.create(:city => "Mumbai",:name =>"Dahisar",:pin_number=>"400068")
Pincode.create(:city => "Mumbai",:name =>"Andheri (E)",:pin_number=>"400069")
Pincode.create(:city => "Mumbai",:name =>"Kurla",:pin_number=>"400070")
Pincode.create(:city => "Mumbai",:name =>"Chembur",:pin_number=>"400071")
Pincode.create(:city => "Mumbai",:name =>"Saki Naka Andheri (E)",:pin_number=>"400072")
Pincode.create(:city => "Mumbai",:name =>"Kurla (W)",:pin_number=>"400072")
Pincode.create(:city => "Mumbai",:name =>"Chembur Vashi Naka",:pin_number=>"400073")
Pincode.create(:city => "Mumbai",:name =>"Chembur",:pin_number=>"400074")
Pincode.create(:city => "Mumbai",:name =>"Pant Nagar Ghatkopar (E)",:pin_number=>"400075")
Pincode.create(:city => "Mumbai",:name =>"I I T Mumbai",:pin_number=>"400076")
Pincode.create(:city => "Mumbai",:name =>"Powai",:pin_number=>"400076")
Pincode.create(:city => "Mumbai",:name =>"Rajawadi Ghatkopar (E)",:pin_number=>"400077")
Pincode.create(:city => "Mumbai",:name =>"Ghatkopar (W)",:pin_number=>"400077")
Pincode.create(:city => "Mumbai",:name =>"Bhandup",:pin_number=>"400078")
Pincode.create(:city => "Mumbai",:name =>"Vikhroli",:pin_number=>"400079")
Pincode.create(:city => "Mumbai",:name =>"Mulund (W)",:pin_number=>"400080")
Pincode.create(:city => "Mumbai",:name =>"Mulund (E)",:pin_number=>"400081")
Pincode.create(:city => "Mumbai",:name =>"Mulund Colony",:pin_number=>"400082")
Pincode.create(:city => "Mumbai",:name =>"Tagore Nagar Vikroli (E)",:pin_number=>"400083")
Pincode.create(:city => "Mumbai",:name =>"Vikhroli",:pin_number=>"400083")
Pincode.create(:city => "Mumbai",:name =>"Barve Nagar Ghatkopar (W)",:pin_number=>"400084")
Pincode.create(:city => "Mumbai",:name =>"Ghatkopar (W)",:pin_number=>"400084")
Pincode.create(:city => "Mumbai",:name =>"B A R C (Trombay)",:pin_number=>"400085")
Pincode.create(:city => "Mumbai",:name =>"Ghatkopar (West)",:pin_number=>"400086")
Pincode.create(:city => "Mumbai",:name =>"N I T I E Vikhroli (W)",:pin_number=>"400087")
Pincode.create(:city => "Mumbai",:name =>"Telecom Factory Deonar",:pin_number=>"400088")
Pincode.create(:city => "Mumbai",:name =>"Deonar (E)",:pin_number=>"400088")
Pincode.create(:city => "Mumbai",:name =>"Tilak Nagar Chembur (w)",:pin_number=>"400089")
Pincode.create(:city => "Mumbai",:name =>"Kurla (W)",:pin_number=>"400089")
Pincode.create(:city => "Mumbai",:name =>"Tilak Nagar",:pin_number=>"400089")
Pincode.create(:city => "Mumbai",:name =>"GOREGAON (W)",:pin_number=>"400090")
Pincode.create(:city => "Mumbai",:name =>"Borivali (E)",:pin_number=>"400091")
Pincode.create(:city => "Mumbai",:name =>"Borivali (W)",:pin_number=>"400092")
Pincode.create(:city => "Mumbai",:name =>"Chakala MIDC",:pin_number=>"400093")
Pincode.create(:city => "Mumbai",:name =>"Andheri (E)",:pin_number=>"400093")
Pincode.create(:city => "Mumbai",:name =>"Anu Shakti Nagar",:pin_number=>"400094")
Pincode.create(:city => "Mumbai",:name =>"MALAD (W)",:pin_number=>"400095")
Pincode.create(:city => "Mumbai",:name =>"Seepz",:pin_number=>"400096")
Pincode.create(:city => "Mumbai",:name =>"Malad (East)",:pin_number=>"400097")
Pincode.create(:city => "Mumbai",:name =>"Vidyanagari",:pin_number=>"400098")
Pincode.create(:city => "Mumbai",:name =>"Sahar Andheri (E) ",:pin_number=>"400099")
Pincode.create(:city => "Mumbai",:name =>"Vile Parle (E)",:pin_number=>"400099")
Pincode.create(:city => "Mumbai",:name =>"Kandivali (E)",:pin_number=>"400101")
Pincode.create(:city => "Mumbai",:name =>"Jogeshwari (W)",:pin_number=>"400102")
Pincode.create(:city => "Mumbai",:name =>"Mandpeshwar Borivali (W)",:pin_number=>"400103")
Pincode.create(:city => "Mumbai",:name =>"Motilal Nagar Goregaon (E)",:pin_number=>"400104")
Pincode.create(:city => "Thane",:name =>"Thane (H Q)",:pin_number=>"400601")
Pincode.create(:city => "Thane",:name =>"Naupada",:pin_number=>"400602")
Pincode.create(:city => "Thane",:name =>"Kopri Colony Thane (W)",:pin_number=>"400603")
Pincode.create(:city => "Thane",:name =>"Thane (E)",:pin_number=>"400603")
Pincode.create(:city => "Thane",:name =>"Wagle Industrial Estate Thane (W)",:pin_number=>"400604")
Pincode.create(:city => "Thane",:name =>"Kalwa",:pin_number=>"400605")
Pincode.create(:city => "Thane",:name =>"Jakegram  Thane (W)",:pin_number=>"400606")
Pincode.create(:city => "Thane",:name =>"Thane (W)",:pin_number=>"400606")
Pincode.create(:city => "Thane",:name =>"Sandoz Baug Thane (E)",:pin_number=>"400607")
Pincode.create(:city => "Thane",:name =>"Thane (E)",:pin_number=>"400607")
Pincode.create(:city => "Thane",:name =>"Balcum  Thane (W)",:pin_number=>"400608")
Pincode.create(:city => "Navi Mumbai",:name =>"Belapur",:pin_number=>"400611")
Pincode.create(:city => "Thane",:name =>"Mumbra",:pin_number=>"400612")
Pincode.create(:city => "Navi Mumbai",:name =>"Turbhe",:pin_number=>"400613")
Pincode.create(:city => "Navi Mumbai",:name =>"Konkan Bhawan Belapur",:pin_number=>"400614")
Pincode.create(:city => "Navi Mumbai",:name =>"Ghansoli",:pin_number=>"400701")
Pincode.create(:city => "Navi Mumbai",:name =>"Turbhe",:pin_number=>"400701")
Pincode.create(:city => "Navi Mumbai",:name =>"Uran",:pin_number=>"400702")
Pincode.create(:city => "Navi Mumbai",:name =>"Vashi",:pin_number=>"400703")
Pincode.create(:city => "Navi Mumbai",:name =>"N A D Karanja (New Panvel)",:pin_number=>"400704")
Pincode.create(:city => "Navi Mumbai",:name =>"Airoli",:pin_number=>"400705")
Pincode.create(:city => "Navi Mumbai",:name =>"Krishi Utpanna Bazar( A P M C BAZAR )",:pin_number=>"400705")
Pincode.create(:city => "Navi Mumbai",:name =>"Turbhe",:pin_number=>"400705")
Pincode.create(:city => "Navi Mumbai",:name =>"Nerul Mode",:pin_number=>"400706")
Pincode.create(:city => "Navi Mumbai",:name =>"JNPT Town Ship",:pin_number=>"400707")
Pincode.create(:city => "Navi Mumbai",:name =>"Airoli Mode",:pin_number=>"400708")
Pincode.create(:city => "Navi Mumbai",:name =>"Koparkhairne",:pin_number=>"400709")
Pincode.create(:city => "Thane",:name =>"Bhayandar",:pin_number=>"401101")
Pincode.create(:city => "Thane",:name =>"Umbarpada (Bhayandar)",:pin_number=>"401102")
Pincode.create(:city => "Thane",:name =>"Vangam (Mira road)",:pin_number=>"401103")
Pincode.create(:city => "Thane",:name =>"Mira road",:pin_number=>"401104")
Pincode.create(:city => "Thane",:name =>"Bhayandar (E)",:pin_number=>"401105")
Pincode.create(:city => "Thane",:name =>"Uttan",:pin_number=>"401106")
Pincode.create(:city => "Thane",:name =>"Mira Road (E)",:pin_number=>"401107")
Pincode.create(:city => "Thane",:name =>"Bassien",:pin_number=>"401201")
Pincode.create(:city => "Thane",:name =>"Bassien Road",:pin_number=>"401202")
Pincode.create(:city => "Thane",:name =>"Sopara",:pin_number=>"401203")
Pincode.create(:city => "Thane",:name =>"Vajreshwari",:pin_number=>"401204")
Pincode.create(:city => "Thane",:name =>"Vasai",:pin_number=>"401205")
Pincode.create(:city => "Thane",:name =>"Ganeshpuri (Khopoli)",:pin_number=>"401206")
Pincode.create(:city => "Thane",:name =>"Papdi",:pin_number=>"401207")
Pincode.create(:city => "Thane",:name =>"Vasai E I/E",:pin_number=>"401208")
Pincode.create(:city => "Thane",:name =>"Nalasopara (E)",:pin_number=>"401209")
Pincode.create(:city => "Thane",:name =>"Vasai Road E",:pin_number=>"401210")
Pincode.create(:city => "Thane",:name =>"Agashi",:pin_number=>"401301")
Pincode.create(:city => "Thane",:name =>"Arnala",:pin_number=>"401302")
Pincode.create(:city => "Thane",:name =>"Virar",:pin_number=>"401303")
Pincode.create(:city => "Thane",:name =>"Nirmal",:pin_number=>"401304")
Pincode.create(:city => "Thane",:name =>"Kelwa",:pin_number=>"401401")
Pincode.create(:city => "Thane",:name =>"Kelwa Mahim",:pin_number=>"401402")
Pincode.create(:city => "Thane",:name =>"Manor",:pin_number=>"401403")
Pincode.create(:city => "Thane",:name =>"Palghar H O",:pin_number=>"401404")
Pincode.create(:city => "Thane",:name =>"Satpati",:pin_number=>"401405")
Pincode.create(:city => "Thane",:name =>"Boisar",:pin_number=>"401501")
Pincode.create(:city => "Thane",:name =>"Tarapur",:pin_number=>"401502")
Pincode.create(:city => "Thane",:name =>"Chinchani",:pin_number=>"401503")
Pincode.create(:city => "Thane",:name =>"Tarapur App",:pin_number=>"401504")
Pincode.create(:city => "Thane",:name =>"Tarapur J/A",:pin_number=>"401506")
Pincode.create(:city => "Thane",:name =>"Dahanu",:pin_number=>"401601")
Pincode.create(:city => "Thane",:name =>"Dahanu Road",:pin_number=>"401602")
Pincode.create(:city => "Thane",:name =>"Jawhar",:pin_number=>"401603")
Pincode.create(:city => "Thane",:name =>"Mokhada",:pin_number=>"401604")
Pincode.create(:city => "Thane",:name =>"Vikramgad",:pin_number=>"401605")
Pincode.create(:city => "Thane",:name =>"Talasari",:pin_number=>"401606")
Pincode.create(:city => "Thane",:name =>"Kasa",:pin_number=>"401607")
Pincode.create(:city => "Thane",:name =>"Suryanagar",:pin_number=>"401609")
Pincode.create(:city => "Thane",:name =>"Dapcheri",:pin_number=>"401610")
Pincode.create(:city => "Thane",:name =>"Bordi",:pin_number=>"401701")
Pincode.create(:city => "Thane",:name =>"Gholvad",:pin_number=>"401702")
Pincode.create(:city => "Thane",:name =>"Kosbad Hill",:pin_number=>"401703")
Pincode.create(:city => "Navi Mumbai",:name =>"Panvel",:pin_number=>"410206")
Pincode.create(:city => "Navi Mumbai",:name =>"Kamotha",:pin_number=>"410209")
Pincode.create(:city => "Navi Mumbai",:name =>"Kharghar",:pin_number=>"410210")
Pincode.create(:city => "Navi Mumbai",:name =>"New Panvel",:pin_number=>"410216")
Pincode.create(:city => "Navi Mumbai",:name =>"Kalamboli",:pin_number=>"410218")
Pincode.create(:city => "Navi Mumbai",:name =>"Kamotha",:pin_number=>"410218")
Pincode.create(:city => "Thane",:name =>"Ulhasnagar",:pin_number=>"421001")
Pincode.create(:city => "Thane",:name =>"Ulhasnagar",:pin_number=>"421002")
Pincode.create(:city => "Thane",:name =>"Ulhasnagar",:pin_number=>"421003")
Pincode.create(:city => "Thane",:name =>"Ulhasnagar",:pin_number=>"421004")
Pincode.create(:city => "Thane",:name =>"Ulhasnagar",:pin_number=>"421005")
Pincode.create(:city => "Thane",:name =>"Dombivali (E)",:pin_number=>"421201")
Pincode.create(:city => "Thane",:name =>"Dombivali (W)",:pin_number=>"421202")
Pincode.create(:city => "Thane",:name =>"Kalyan",:pin_number=>"421301")
Pincode.create(:city => "Thane",:name =>"Bhiwandi",:pin_number=>"421302")
Pincode.create(:city => "Thane",:name =>"Kalyan",:pin_number=>"421304")
Pincode.create(:city => "Thane",:name =>"Kalyan",:pin_number=>"421306")
Pincode.create(:city => "Thane",:name =>"Ambernath",:pin_number=>"421501")
Pincode.create(:city => "Thane",:name =>"Titwala",:pin_number=>"421503")
Pincode.create(:city => "Thane",:name =>"Murbad",:pin_number=>"421504")
Pincode.create(:city => "Thane",:name =>"Titwala",:pin_number=>"421504")
Pincode.create(:city => "Thane",:name =>"Badlapur",:pin_number=>"421506")
Pincode.create(:city => "Navi Mumbai",:name =>"Turbhe",:pin_number=>"400613")
Pincode.create(:city => "Navi Mumbai",:name =>"Vashi",:pin_number=>"400703")
Pincode.create(:city => "Thane",:name =>"VASAI",:pin_number=>"401301")
Pincode.create(:city => "Thane",:name =>"THANE",:pin_number=>"401303")
Pincode.create(:city => "Thane",:name =>"PALGHAR",:pin_number=>"401504")
Pincode.create(:city => "Thane",:name =>"KHOPOLI",:pin_number=>"410203")
Pincode.create(:city => "Navi Mumbai",:name =>"Kharghar",:pin_number=>"410210")
Pincode.create(:city => "Thane",:name =>"Shahad",:pin_number=>"421001")
Pincode.create(:city => "Thane",:name =>"Thakurli",:pin_number=>"421202")
Pincode.create(:city => "Thane",:name =>"Bhiwandi",:pin_number=>"421302")
Pincode.create(:city => "Thane",:name =>"THANE",:pin_number=>"421601")





Branch.create( :name=>"ANDHERI E", :branch_code => "00539" , :client_id => 1)
Branch.create( :name=>"ANDHERI E SEEPZ", :branch_code => "11690" , :client_id => 1)
Branch.create( :name=>"ANDHERI SAHAR RD", :branch_code => "05937" , :client_id => 1)
Branch.create( :name=>"ANDHERI W", :branch_code => "13204" , :client_id => 1)
Branch.create( :name=>"ANDHERI W LOKHNDWALA", :branch_code => "04276" , :client_id => 1)
Branch.create( :name=>"ANDHERI WEST", :branch_code => "04650" , :client_id => 1)
Branch.create( :name=>"AUNDH PUNE", :branch_code => "08784" , :client_id => 1)
Branch.create( :name=>"BADLAPUR INDUSTRIAL ESTATE", :branch_code => "07452" , :client_id => 1)
Branch.create( :name=>"BANDRA W", :branch_code => "00548" , :client_id => 1)
Branch.create( :name=>"BHANDUP LBS", :branch_code => "00562" , :client_id => 1)
Branch.create( :name=>"BHAYANDER", :branch_code => "05318" , :client_id => 1)
Branch.create( :name=>"BHIWANDI ", :branch_code => "00331" , :client_id => 1)
Branch.create( :name=>"BHULABHAI RD", :branch_code => "05340" , :client_id => 1)
Branch.create( :name=>"BKC", :branch_code => "04380" , :client_id => 1)
Branch.create( :name=>"BORIVLI WEST", :branch_code => "00551" , :client_id => 1)
Branch.create( :name=>"BYCULLA", :branch_code => "00343" , :client_id => 1)
Branch.create( :name=>"CAMP-4 ULHASNAGAR", :branch_code => "12702" , :client_id => 1)
Branch.create( :name=>"CBD BELAPUR", :branch_code => "13551" , :client_id => 1)
Branch.create( :name=>"CHEMBUR MAHUL RD", :branch_code => "00564" , :client_id => 1)
Branch.create( :name=>"CHEMBUR NRI ", :branch_code => "16228" , :client_id => 1)
Branch.create( :name=>"COLABA", :branch_code => "10716" , :client_id => 1)
Branch.create( :name=>"CUFFE PARADE", :branch_code => "05345" , :client_id => 1)
Branch.create( :name=>"DADAR", :branch_code => "00353" , :client_id => 1)
Branch.create( :name=>"DEONAR", :branch_code => "03109" , :client_id => 1)
Branch.create( :name=>"DIAMOND GARDEN", :branch_code => "13340" , :client_id => 1)
Branch.create( :name=>"DOMBIVALI E PHASE I", :branch_code => "01595" , :client_id => 1)
Branch.create( :name=>"DOMBIVALI EAST", :branch_code => "07124" , :client_id => 1)
Branch.create( :name=>"DOMBIVALI INDUSTRIAL ESTATE BR", :branch_code => "01595" , :client_id => 1)
Branch.create( :name=>"DOMBIVLI WEST BRANCH ", :branch_code => "05165" , :client_id => 1)
Branch.create( :name=>"FINANCE VASHI BR", :branch_code => "11706" , :client_id => 1)
Branch.create( :name=>"GHANSOLI", :branch_code => "13033" , :client_id => 1)
Branch.create( :name=>"GHANSOLI", :branch_code => "12965" , :client_id => 1)
Branch.create( :name=>"GHATKOPAR E", :branch_code => "00516" , :client_id => 1)
Branch.create( :name=>"GHATKOPAR M G RD", :branch_code => "60203" , :client_id => 1)
Branch.create( :name=>"GHATKOPAR PANTNAGAR", :branch_code => "11711" , :client_id => 1)
Branch.create( :name=>"GHATKOPAR W GRD", :branch_code => "01131" , :client_id => 1)
Branch.create( :name=>"GHATKOPAR W1", :branch_code => "01131" , :client_id => 1)
Branch.create( :name=>"GOREGAON W", :branch_code => "01266" , :client_id => 1)
Branch.create( :name=>"HIRANANDANI", :branch_code => "11708" , :client_id => 1)
Branch.create( :name=>"HOUSING FINANCE BR.VASHI", :branch_code => "11706" , :client_id => 1)
Branch.create( :name=>"IGATPURI ", :branch_code => "00386" , :client_id => 1)
Branch.create( :name=>"JUINAGAR", :branch_code => "11786" , :client_id => 1)
Branch.create( :name=>"KALMBOLI", :branch_code => "12701" , :client_id => 1)
Branch.create( :name=>"KALYAN BAZARPETH ROAD", :branch_code => "12925" , :client_id => 1)
Branch.create( :name=>"KALYAN E", :branch_code => "15250" , :client_id => 1)
Branch.create( :name=>"KALYAN KHADAKPADDA", :branch_code => "11159" , :client_id => 1)
Branch.create( :name=>"KALYAN W ", :branch_code => "00399" , :client_id => 1)
Branch.create( :name=>"KANDIVALI E SAHAKARGRAM", :branch_code => "30281" , :client_id => 1)
Branch.create( :name=>"KANJURMARG E", :branch_code => "06249" , :client_id => 1)
Branch.create( :name=>"KEMS CORNER", :branch_code => "06994" , :client_id => 1)
Branch.create( :name=>"KERALA", :branch_code => "08589" , :client_id => 1)
Branch.create( :name=>"KHARGHAR BRANCH SEC.21 ", :branch_code => "11673" , :client_id => 1)
Branch.create( :name=>"KHARGHAR BRANCH SEC.35 ", :branch_code => "15972" , :client_id => 1)
Branch.create( :name=>"KHOPOLI", :branch_code => "05551" , :client_id => 1)
Branch.create( :name=>"KOKAN BHAVAN", :branch_code => "06240" , :client_id => 1)
Branch.create( :name=>"KOPARKHAIRANE", :branch_code => "10331" , :client_id => 1)
Branch.create( :name=>"KURLA", :branch_code => "01886" , :client_id => 1)
Branch.create( :name=>"KURLA LBS", :branch_code => "12703" , :client_id => 1)
Branch.create( :name=>"LALBAUG", :branch_code => "01850" , :client_id => 1)
Branch.create( :name=>"LOWER PAREL BRANCH  (N.M.JOSHI)", :branch_code => "3428" , :client_id => 1)
Branch.create( :name=>"MAJIWADE(THANE)", :branch_code => "13377" , :client_id => 1)
Branch.create( :name=>"MALAD E", :branch_code => "03110" , :client_id => 1)
Branch.create( :name=>"MALAD MARVE", :branch_code => "03280" , :client_id => 1)
Branch.create( :name=>"MARAL BR (OUT OF MAHARASHTRA)", :branch_code => "16325" , :client_id => 1)
Branch.create( :name=>"MATUNGA", :branch_code => "05350" , :client_id => 1)
Branch.create( :name=>"MULUND EAST", :branch_code => "04210" , :client_id => 1)
Branch.create( :name=>"MULUND GAVANPADA", :branch_code => "13034" , :client_id => 1)
Branch.create( :name=>"MULUND HARI OM NAGAR", :branch_code => "16878" , :client_id => 1)
Branch.create( :name=>"MULUND LBS RD", :branch_code => "11672" , :client_id => 1)
Branch.create( :name=>"MULUND W DEVIDAYAL RD", :branch_code => "16720" , :client_id => 1)
Branch.create( :name=>"MULUND WEST", :branch_code => "03225" , :client_id => 1)
Branch.create( :name=>"MUMBAI CENTRAL", :branch_code => "00547" , :client_id => 1)
Branch.create( :name=>"NALASOPARA W", :branch_code => "10414" , :client_id => 1)
Branch.create( :name=>"NAUPADA ", :branch_code => "04498" , :client_id => 1)
Branch.create( :name=>"NEHRU NGR KURLA E", :branch_code => "12924" , :client_id => 1)
Branch.create( :name=>"NERUL WEST", :branch_code => "05087" , :client_id => 1)
Branch.create( :name=>"NERUL(EAST)", :branch_code => "11785" , :client_id => 1)
Branch.create( :name=>"NEW PANVEL", :branch_code => "60383" , :client_id => 1)
Branch.create( :name=>"NEW PANVEL", :branch_code => "11758" , :client_id => 1)
Branch.create( :name=>"NEW PANVEL WEST (SECTOR-6)", :branch_code => "15664" , :client_id => 1)
Branch.create( :name=>"OLD PANVEL", :branch_code => "00448" , :client_id => 1)
Branch.create( :name=>"PALGHAR", :branch_code => "00444" , :client_id => 1)
Branch.create( :name=>"PALGHAR SAPHALE", :branch_code => "13822" , :client_id => 1)
Branch.create( :name=>"PAREL BRANCH", :branch_code => "01884" , :client_id => 1)
Branch.create( :name=>"PEDDER ROAD", :branch_code => "00510" , :client_id => 1)
Branch.create( :name=>"POWAI", :branch_code => "01109" , :client_id => 1)
Branch.create( :name=>"RABALE", :branch_code => "03375" , :client_id => 1)
Branch.create( :name=>"RASAYANI", :branch_code => "2172" , :client_id => 1)
Branch.create( :name=>"S.I.B GHATKOPAR(W)", :branch_code => "04832" , :client_id => 1)
Branch.create( :name=>"SALTLAKE", :branch_code => "04204" , :client_id => 1)
Branch.create( :name=>"SANPADA BRANCH", :branch_code => "05141" , :client_id => 1)
Branch.create( :name=>"SANTACRUZ E", :branch_code => "13265" , :client_id => 1)
Branch.create( :name=>"SBI BAPMC BRANCH ", :branch_code => "09961" , :client_id => 1)
Branch.create( :name=>"SBI NRI BRANCH SHEWOOD", :branch_code => "16215" , :client_id => 1)
Branch.create( :name=>"SBI WASHI TURBHE BRANCH", :branch_code => "03736" , :client_id => 1)
Branch.create( :name=>"SBI, KHANDESHWAR BR", :branch_code => "16374" , :client_id => 1)
Branch.create( :name=>"SECTOR 20 KOPERKHAIRANE BR", :branch_code => "15284" , :client_id => 1)
Branch.create( :name=>"SECTOR-10 VASHI", :branch_code => "30419" , :client_id => 1)
Branch.create( :name=>"SENAPATI BAPAT MARG BRANCH", :branch_code => "13757" , :client_id => 1)
Branch.create( :name=>"SHIVAJI PARK DADAR BR", :branch_code => "01429" , :client_id => 1)
Branch.create( :name=>"SHIVAJI TALAV BHANDUP", :branch_code => "15474" , :client_id => 1)
Branch.create( :name=>"SHRIWARDHAN", :branch_code => "01049" , :client_id => 1)
Branch.create( :name=>"SION", :branch_code => "04296" , :client_id => 1)
Branch.create( :name=>"SWASTIK PARK ", :branch_code => "07192" , :client_id => 1)
Branch.create( :name=>"THANE EAST", :branch_code => "07232" , :client_id => 1)
Branch.create( :name=>"THANE GHODBUNDER RD", :branch_code => "10786" , :client_id => 1)
Branch.create( :name=>"THANE J K MARG", :branch_code => "09056" , :client_id => 1)
Branch.create( :name=>"THANE MAIN ", :branch_code => "00489" , :client_id => 1)
Branch.create( :name=>"THANE PANCHPAKHADI", :branch_code => "11674" , :client_id => 1)
Branch.create( :name=>"THANE SAKET RD", :branch_code => "16417" , :client_id => 1)
Branch.create( :name=>"THANE VASANT VIHAR", :branch_code => "04314" , :client_id => 1)
Branch.create( :name=>"THANE W E", :branch_code => "01053" , :client_id => 1)
Branch.create( :name=>"TITWALA", :branch_code => "16389" , :client_id => 1)
Branch.create( :name=>"ULHASNAGAR NO 3", :branch_code => "01202" , :client_id => 1)
Branch.create( :name=>"VAISHALI NGR MULUND", :branch_code => "15149" , :client_id => 1)
Branch.create( :name=>"VAKOLA BRANCH", :branch_code => "01467" , :client_id => 1)
Branch.create( :name=>"VASAI", :branch_code => "00326" , :client_id => 1)
Branch.create( :name=>"VASHI BRANCH", :branch_code => "14677" , :client_id => 1)
Branch.create( :name=>"VASHI NAVI MUMBAI", :branch_code => "10330" , :client_id => 1)
Branch.create( :name=>"VASHI SEC 14", :branch_code => "15285" , :client_id => 1)
Branch.create( :name=>"VASHI SECTOR-19 ,VASHI", :branch_code => "60347" , :client_id => 1)
Branch.create( :name=>"VERSOVA", :branch_code => "03117" , :client_id => 1)
Branch.create( :name=>"VIDYAVIHAR", :branch_code => "11710" , :client_id => 1)
Branch.create( :name=>"VIKHROLI E", :branch_code => "07212" , :client_id => 1)
Branch.create( :name=>"VIKHROLI W", :branch_code => "01406" , :client_id => 1)
Branch.create( :name=>"VILE PARLE E", :branch_code => "01174" , :client_id => 1)
Branch.create( :name=>"VILE PARLE W IRLA", :branch_code => "15713" , :client_id => 1)
Branch.create( :name=>"WODEHOUSE ROAD COLABA", :branch_code => "00572" , :client_id => 1)

Client.create(name: 'SBI')

['A/C OFFICER MTNL','ACCESS SYSTEM','ACCOUNT & FINANCE MANAGER','ACCOUNT FINANCE','ACCOUNTANT AUDIT','ADDITIONAL','ADMINISTRATOR','ADVANCED CENTER FOR WOMEN RESEARCH','ADVISOR','AGRICULTURE','AGRICULTURE SERVICES','AIRCRAFT','MAINTENANCE ENGINEERING','ALLOTMENT LETTER','ANALAYZE','ANALTST','ANALYSE','ANALYST','ANIMAL HUSBANDRY','APPLICATION ANALYSE','APPLICATION DEVLOPMENT','APPORVAL','ARCHITECT','ASSEMBLY','ASSEMBLY FITTER','ASSISTANCE  MANAGER','ASSISTANCE GENRAL MANAGER','ASSISTANT','COMPUTER OPREATOR','ASSISTANT CONSULTANCY','ASSISTANT ENGGINER','ASSISTANT FOREMAN','ASSISTANT LAW OFFICER','ASSISTANT LOCO','PILOT','ASSISTANT MANAGER','ASSISTANT PROFESSOR','ASSISTANT SALES MANAGER','ASSISTANT SUPERINTENDENT','ASSISTANT TEACHER','ASSISTANT WISE','PRESIDENT & DELIVERY MANAGER','ASSIT  CONSULTANCY','ASSIT COMPUTER OPREATOR ','ASSIT PROFESSOR','ASSOCIAITE','ASSOCIAITE PROFESSOR','SENIOR GREAT','ASSOCIAITE VICE PRESIDENT','ASSOCIATE','ASSOCIATE SOCIAL MEDIA','ASTROLOGY','ATOMIC ENERGY','AUDIT DIRECTOR','AUDITOR','AUTOMOBILE ENGINEERING','BIOSCINES','BMC MUNCIPAL CORPORATION','BUILDING & FACTORIES DEVELOPER','BUSINESS AUDIT','BUSINESS DEVELOPER','BUSINESS DEVELOPMENT MANAGER','BUSINESS ENABLING TEAM','BUSINESS RESEARCH','BYO CHEMISTRY','C.A LICENCE','CONSALTUNT','CARGO INCHARG','CASIER','CENTRAL EXCISE MUMBAI III','CHANNEL SALES EXECUTIVE','CHEMICAL','CHEMISTRY','CHIEF AIRCRAFT','OPERATOR','CHIEF ENGINEER','CHIEF FINANCE CONSULTANT','CHIF STAFF INSPECTOR','CIVIL CONSTRUCTION','CLERK','CLERK CUM TYPIST','CLIENT','SERVICES','COAL LOGISTICS FOR POWER PLANTS','COMMANDER','COMMERCIAL','COMMISSION OF CENTRAL EXCISE REVENUE','COMPARTMENT','COMPLIANCE','COMPLIMENTARY ANUR VECHIL MEDICS','COMPUTER TECHNICAL','CONDUCTOR','CONSTRUCTION','CONSTRUCTION MANAGEMENT','CONSULTANCE','CONSULTANCY','CONSULTANT','CONTAINER MAINTENANCE','CO-ORDINATOR','CORPORATE ACTIONS','COUNSELLOR','CREADIT MANAGER','CREATIVE','CUSTOMER SERVICE','D.Y. COMMISSIONER','DAUGHTER','DEPUTY','DEPUTY CHIFE OFFICER','DEPUTY COMMISINOR','DEPUTY COMMISSIONER','DEPUTY DIRECTOR','DEPUTY DIRECTOR OF TOWN PLANNING','DEPUTY ENGINEER','DEPUTY GENRAL','DEPUTY GENRAL MANAGER','DEPUTY MANAGER','DEPUTY MANAGER TECHNICAL','DEPUTY PROJECT DIRECTOR','DESIGNER','DESINOR','DESK OFFICER','DEVELOPMENT','DEVLOPMENT','DGM (DEPUTY,GERNERAL MANAGER)','DIRECTOR','DIRECTOR PROPERITOR','DIRECTOR REFAR','DISTRACTION','DRILLING','DRIVER','DUTY OFFICER','EDUCATION','ELECTRICAL MANAGER','ELECTRICIAN','ELECTRONICS','ENDOCRINOLOGY','ENGG ELECTRICAL','ENGGINERING','ENGGINERING ELECTRICAL','EQUIPMENT OPERATOR','ESTABLISHMENT','EXCHANGE','EXCUTIVE SALES SUPPORTS','EXECUTIVE','EXECUTIVE  SECRETARIES','EXECUTIVE','ASSISTANT MANAGING DIRECTOR','EXECUTIVE ENGINEER','EXPORT IMPORT','FACILITY','FINANCIAL','PARMACY','FINANCE','FINANCE &ACTSFINANCIAL','FINANCIAL CONTROLLER','FIREBRIGDE','FITTER','FRIEND','FRIENDS','FRIND OFFICE','GENRAL MANAGER','GENRAL MANAGER IN BUSSINESS','DEVELOPMENT' ,'GLOBAL TEKNOLOJI DEVELOPMENT','GLOBLE  RISK LABORATORY','GRAFISH','GROUND HANDLING','HAIRDRESSER & MAKEUP ARTIST','HEAD CONSATBLE','HEAD QTRS','HEALTH','HIGHER GRADE ASSISTANT','HYDRO QUEBEC','IMPLEMENTATION','INDUSTRIAL','INDUSTRIAL AUTOMATION','INFORMATION','INFORMATION TECHNOLOGY SOFTWARE','INFRASTRUCTURE','INFRATECH MANAGEMENT CONSULTANTS','INSORT','INSPECTOR','INSURANCE','INTEGRATION','INTEGRATOR','INTERIO-LAB','INTERIOR','INTERNATIONAL BUSINESS','INTERVIWE','INVESTMENT','HELP SAFETY','JOINT COMMISSIONER','JOUNIOR ENGINEERING','JUNIOR','JUNIOR CLERK','JUNIOR ELECTRICAL ENGINEER','JUNIOR TECHNICAL SUPERINTENDENT','JUNIOR TECHNICIAN','LAB TECHNICHAN','LABORATORY','LACTURALE','LASCAR','LEADER','LECTURER','LECTURERS','LEICA MICROSYSTEM SERVICE','LOGHISTIC MANAGER','M.S.C.AGRICULTURE','MAC ENGINEERING','MAHARASHTRA JEEVAN PRADHIKARAN' ,'MAINTENANCE','MAJOR ARCHITECT MANAGER','MANAGEMENT','OPERATIONS','MANAGING DIRECTOR','MANUFACTURING','MARKET SECURTY' ,'MARKET SECURTY','MATERIAL MANAGEMENT','MEASUREMENT','MECHANICAL ENGINEERING','MECHANICAL OPERATOR','MEDICINE','METER READING','MICROBIOLOGY','MINISTERING BRODCASTING','MOTOR TRANSFER FUNCTION','MSC AGRICULTURE','NATIONAL','NATIONAL SALES MANAGER','NETWORK SOLUTIONS','OFFICE MANAGEMENT STAFF','OPERATING','OPERATION & MAINTENANCE','OPERATION MANAGER','OPERATOR','OPTOMETRIST','ORTHOPEDIC','PANCHAYAT COMMITTEE','PARTNER','PASSENGER','GARD' ,'PATHOLOGY','PENSION','PEON','PERSONAL DATA BASE','PERSONAL EXECUTIVE','PHARMACYS','PHARMACYS SECTION','PHILOSOPHY','PHILOSOPHY','POLICE COMMISSIONER','POLICE CONSTABLE','POLICE CONSTEBAL','POLLUTION LAW DIVISION','POST ELECTRICAL','MANAGER','POST JUNIOR CLERK','POST SENIOR ANALYST','POSTGRADUATE DIPLOMA IN FORESTRY','PREMIER WEALTH MANAGER','PRIMESES','PRINCIPAL SEINE','PRIVATE EQUITY','PROCESS','PROCUREMENT','PRODUCT','PRODUCTION','PROFESSION IS','PROFESSOR','PROGRAMER','PROJECT','PROPOSAL','PROPRIETOR','PUBLIC & MORTALITY','PURCHASE' ,'PURCHASE MANAGER','QUALIFICATION' ,'QULITY CONTROL','REACTOR SAFETY','REGINAL SELES MANAGER','REGISTER','REGISTRAR MEDICAL','REGULATING','REGULATORY AFFAIRS','REGULATORY EXECUTIVE','RELATIONSHIP','REPAIR WALL','RESEARCH & DEVELOPMENT AGRICULTURE','RESEARCH ASSOCIATE','RESEARCH LABORATORY','RESERCH','RESPONDED','REVENUE','REVENUE ACCOUNT','RISK MANAGEMENT','SALES COORDINATOR','SALES SCHEME','SALES TEAM LEADER','SCIENTIFIC','OFFICER','SCIENTIST','SECOND OFFICER','SECRETARIAL' ,'SECRETARY','SECTION','SECURITY','SELES CO-ORDINATOR','SENIOR ACCOUNTANT','SENIOR ADVISOR &CONSULTANT','SENIOR ANALYST','SENIOR ASSISTANT CONSULTANT','SENIOR AUDITOR','SENIOR CAD MANAGER TECHNICIAN','SENIOR CLERK,SENIOR CONDUCTION','SENIOR CONSULTANT','SENIOR CLERK','SENIOR DUPTY ENGINEER','SENIOR ENGINEER','SENIOR EXECUTIVE','SENIOR GENERAL MANAGER','SENIOR INSPECTOR','SENIOR MANAGER','SENIOR OFFICER GRAED 1' ,'SENIOR PHARMACYS','SENIOR PRODUCTION ENGG','SENIOR RELATIONSHIP MANAGER','SENIOR RESEARCH ANALYST','SENIOR SECTION SUPERVISIOR','SENIOR SECTION SUPERVISIOR.','SENIOR SERVICE','ENGINEER','SENIOR SPECIALIST','SENIOR STENOGRAPHER','SENIOR TECHNICIAN','SENIOR TERRITORY','SENIOUR ADMINISTRATOR','SENIOUR EXECUTIVE','SENOIR HR ADMIN','SERVICE','SERVICE ENGINEER','STAFF NURSE','SHOP & ESTABLISHMENT LICENSE','SENIOR VICE PRESIDENT','SISTHA','PATHOLOGY','SITE ENGINEER','SOFTWARE','SOFTWARE ENGINEER','SPECIALIST','SPECILSED','SR. MEDICAL ADVISOR','STABILITY OFFICER','STAFF','STAFF NURSE','STATE INTELLIGENCE','STATIONARY','STENOGRAPHER','STOCK EXCHANGE','STRUCTURAL ENGINEERING','SUPERINTENDENT','SUPERVISIOR','SUPPLY CHAIN (PRODUCTION)','SUPPLY CHAIN MANAGER','SUPPORT','SURVIVOR','SYBASE UNWIRED PLATFORM','SYSTEM','SYSTEM ADMINISTRATOR','TAHSILDAR','TEACHER','TECHNICAL','TECHNICAL MANAGER','TECHNICAL OFFICER','TECHNICAL SOFTWARE ENGINEER','TECHNICAN','TECHNOLOGY','TEST ENGINEER','TESTING','TESTING SOGETI','TEXCEL','TEXSTYLE','THREE DESGNIOR','TOWN PLANNING' ,'TRAFFIC','TRAFFIC','CONTROLLER','TRANSPORT','TRANSPORTATION','TRANSPORT POLICE CONSTABAL.','TUITION','TYPIST','UNDER SECURITY','UNDERWRITING','UTELITE','UTILITIES','VICE PRESIDENT','VIGILENCE','VIGILENCE  ELECTRICAL  SUPPLY','VICE PRESIDENT','YOGA THERAPIST'].each do |department|
  d = Department.find_or_create_by_name(department)
end


@address = AddressProof.create([{ name: 'Ration Card' }, { name: 'Electricity Bill'},
                     { name: 'Telephone Bill'}, { name: 'Bank Statement card'},
                     { name: 'Driving licence'}, { name: 'Passport'}])

@b_documents = BDocument.create([{ name: 'Employee Card' }, { name: 'Salary Slip'},
                     { name: 'Mobile Bill'}, { name: 'Pan Card'}])


@asset = Asset.create([{ name: 'TV'}, { name: 'Air Conditioner'}, { name: 'Refrigrator'}, { name: 'Music System'}])

@office_asset = OfficeAsset.create([{name: 'Telephones'}, {name: 'Computer'},{name: 'Fax'}, {name: 'AC'}, {name: 'Photocopier'}])

   Tab.create( :name=>"TAB-ANDHERI", :tab_code=>'T0102030')
   Tab.create( :name=>"TAB-VIKROLI", :tab_code=>'T0102031')
   Tab.create( :name=>"TAB-SION", :tab_code=>'T0102032')
