# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

    @address = AddressProof.create([{ name: 'Ration Card' }, { name: 'Electricity Bill'},
                         { name: 'Telephone Bill'}, { name: 'Bank Statement card'},
                         { name: 'Driving licence'}, { name: 'Passport'}])


    @asset = Asset.create([{ name: 'TV'}, { name: 'Air Conditioner'}, { name: 'Refrigrator'}, { name: 'Music System'}])

    @office_asset = OfficeAsset.create([{name: 'Telephones'}, {name: 'Computer'},{name: 'Fax'}, {name: 'AC'}, {name: 'Photocopier'}])

            Tab.create( :name=>"TAB-ANDHERI", :tab_code=>'T0102030')
            Tab.create( :name=>"TAB-JOGESHWARI", :tab_code=>'T0102031')
            Tab.create( :name=>"TAB-GOREGAON", :tab_code=>'T0102032')
            Tab.create( :name=>"TAB-MALAD", :tab_code=>'T0102033')
            Tab.create( :name=>"TAB-VIKROLI", :tab_code=>'T0102034')
            Tab.create( :name=>"TAB-SION", :tab_code=>'T0102035')
            Tab.create( :name => "TAB-MAHAKALI", :tab_code =>'T3434890')

   Pincode.create(:name =>"Fort", :pin_number=>400001 )
   Pincode.create(:name =>"Kalbadevi", :pin_number=>400002 )
   Pincode.create(:name =>"Masjid(e)", :pin_number=>400003 )
   Pincode.create(:name =>"Girgaum", :pin_number=>400004 )
   Pincode.create(:name =>"Colaba", :pin_number=>400005 )
   Pincode.create(:name =>"Malabar hill", :pin_number=>400006 )
   Pincode.create(:name =>"Grant Road", :pin_number=>400007 )
   Pincode.create(:name =>"Mumbai Central", :pin_number=>400008 )
   Pincode.create(:name =>"Masjid(w)", :pin_number=>400009 )
   Pincode.create(:name =>"Mazgaon", :pin_number=>400010 )
   Pincode.create(:name =>"Jacob Circle", :pin_number=>400011 )
   Pincode.create(:name =>"lalbaug", :pin_number=>400012 )
   Pincode.create(:name =>"delisle road", :pin_number=>400013 )
   Pincode.create(:name =>"Dadar", :pin_number=>400014 )
   Pincode.create(:name =>"Sewree", :pin_number=>400015 )
   Pincode.create(:name =>"Mahim", :pin_number=>400016 )
   Pincode.create(:name =>"Dharavi", :pin_number=>400017 )
   Pincode.create(:name =>"Worli", :pin_number=>400018 )
   Pincode.create(:name =>"Matunga Central", :pin_number=>400019 )
   Pincode.create(:name =>"Churchgate", :pin_number=>400020 )
   Pincode.create(:name =>"Nariman Point", :pin_number=>400021 )
   Pincode.create(:name =>"Sion", :pin_number=>400022 )
   Pincode.create(:name =>"Dalal Street", :pin_number=>400023 )
   Pincode.create(:name =>"Kurla", :pin_number=>400024 )
   Pincode.create(:name =>"Prabhadevi", :pin_number=>400025 )
   Pincode.create(:name =>"Fort", :pin_number=>400026 )
   Pincode.create(:name =>"Byculla(e)", :pin_number=>400027 )
   Pincode.create(:name =>"Dadar", :pin_number=>400028 )
   Pincode.create(:name =>"Santacruz(e)", :pin_number=>400029 )
   Pincode.create(:name =>"PGMS Office", :pin_number=>400030 )
   Pincode.create(:name =>"Wadala", :pin_number=>400031 )
   Pincode.create(:name =>"Mantralaya", :pin_number=>400032 )
   Pincode.create(:name =>"Cotton Green", :pin_number=>400033 )
   Pincode.create(:name =>"Haji Ali", :pin_number=>400034 )
   Pincode.create(:name =>"Raj Bhavan", :pin_number=>400035 )
   Pincode.create(:name =>"Kemps corner", :pin_number=>400036 )
   Pincode.create(:name =>"Antop hill", :pin_number=>400037 )
   Pincode.create(:name =>"Ballard Pier", :pin_number=>400038 )
   Pincode.create(:name =>"Ballard Estate", :pin_number=>400039 )
   Pincode.create(:name =>"Jogeshwari(e)", :pin_number=>400041 )
   Pincode.create(:name =>"Bhandup", :pin_number=>400042 )
   Pincode.create(:name =>"Mankhurd", :pin_number=>400043 )
   Pincode.create(:name =>"Vile Parle(e)", :pin_number=>400047 )
   Pincode.create(:name =>"Andheri(w)", :pin_number=>400048 )
   Pincode.create(:name =>"Andheri(w)", :pin_number=>400049 )
   Pincode.create(:name =>"bandra", :pin_number=>400050 )
   Pincode.create(:name =>"Khar", :pin_number=>400051 )
   Pincode.create(:name =>"Khar", :pin_number=>400052 )
   Pincode.create(:name =>"Andheri(w)", :pin_number=>400053 )
   Pincode.create(:name =>"Santacruz(w)", :pin_number=>400054 )
   Pincode.create(:name =>"Santacruz(e)", :pin_number=>400055 )
   Pincode.create(:name =>"Vile parle(w)", :pin_number=>400056 )
   Pincode.create(:name =>"Vile Parle(e)", :pin_number=>400057 )
   Pincode.create(:name =>"Andheri(e)", :pin_number=>400058 )
   Pincode.create(:name =>"Andheri(w)", :pin_number=>400059 )
   Pincode.create(:name =>"Jogeshwari(e)", :pin_number=>400060 )
   Pincode.create(:name =>"Andheri(w)", :pin_number=>400061 )
   Pincode.create(:name =>"Goregaon(w)", :pin_number=>400062 )
   Pincode.create(:name =>"Goregaon(e)", :pin_number=>400063 )
   Pincode.create(:name =>"Malad(w)", :pin_number=>400064 )
   Pincode.create(:name =>"Goregoan(e)", :pin_number=>400065 )
   Pincode.create(:name =>"Borivali(e)", :pin_number=>400066 )
   Pincode.create(:name =>"Kandivali(w)", :pin_number=>400067 )
   Pincode.create(:name =>"Dahisar", :pin_number=>400068 )
   Pincode.create(:name =>"Andheri(e)", :pin_number=>400069 )
   Pincode.create(:name =>"Kurla", :pin_number=>400070 )
   Pincode.create(:name =>"Chembur", :pin_number=>400071 )
   Pincode.create(:name =>"Andheri(e)", :pin_number=>400072 )
   Pincode.create(:name =>"Chembur", :pin_number=>400074 )
   Pincode.create(:name =>"Ghatkopar", :pin_number=>400075 )
   Pincode.create(:name =>"Powai", :pin_number=>400076 )
   Pincode.create(:name =>"Ghatkopar", :pin_number=>400077 )
   Pincode.create(:name =>"Bhandup", :pin_number=>400078 )
   Pincode.create(:name =>"Vikroli", :pin_number=>400079 )   
   Pincode.create(:name =>"Mulund", :pin_number=>400080 )
   Pincode.create(:name =>"Mulund", :pin_number=>400081 )
   Pincode.create(:name =>"Mulund", :pin_number=>400082 )
   Pincode.create(:name =>"Vikroli", :pin_number=>400083 )
   Pincode.create(:name =>"Ghatkopar", :pin_number=>400084 )
   Pincode.create(:name =>"Ghatkopar", :pin_number=>400086 )
   Pincode.create(:name =>"Niete", :pin_number=>400087 )
   Pincode.create(:name =>"Deonar", :pin_number=>400088 )
   Pincode.create(:name =>"Chembur", :pin_number=>400089 )
   Pincode.create(:name =>"Goregaon(w)", :pin_number=>400090 )
   Pincode.create(:name =>"Borivali(w)", :pin_number=>400091 )
   Pincode.create(:name =>"Borivali(w)", :pin_number=>400092 )
   Pincode.create(:name =>"Andheri(e)", :pin_number=>400093 )
   Pincode.create(:name =>"Malad(e)", :pin_number=>400097 )
   Pincode.create(:name =>"Santacruz(e)", :pin_number=>400098 )
   Pincode.create(:name =>"Andheri(e)", :pin_number=>400099 )
   Pincode.create(:name =>"Kandivali(e)", :pin_number=>400101 )
   Pincode.create(:name =>"Jogeshwari(w)", :pin_number=>400102 )
   Pincode.create(:name =>"Borivali(w)", :pin_number=>400103 )
   Pincode.create(:name =>"Goregaon(w)", :pin_number=>400104 )
   Pincode.create(:name =>"Bhayandar(e)", :pin_number=>400105 )
   Pincode.create(:name =>"Goregaon(w)", :pin_number=>400106 )

   Pincode.create(:name =>"Thane", :pin_number=>400601 )
   Pincode.create(:name =>"Thane", :pin_number=>400602 )
   Pincode.create(:name =>"Thane", :pin_number=>400603 )
   Pincode.create(:name =>"Thane", :pin_number=>400604 )
   Pincode.create(:name =>"Kalwa", :pin_number=>400605 )
   Pincode.create(:name =>"Thane", :pin_number=>400606 )
   Pincode.create(:name =>"Thane", :pin_number=>400607 )
   Pincode.create(:name =>"Thane", :pin_number=>400608 )

   Pincode.create(:name =>"Mumbra", :pin_number=>400612 )
   Pincode.create(:name =>"Turbhe", :pin_number=>400613 )
   Pincode.create(:name =>"CBD", :pin_number=>400614 )
   Pincode.create(:name =>"Ghansoli", :pin_number=>400701 )
   Pincode.create(:name =>"Uran", :pin_number=>400702 )
   Pincode.create(:name =>"Vashi", :pin_number=>400703 )
   Pincode.create(:name =>"Vashi", :pin_number=>400704 )
   Pincode.create(:name =>"Vashi", :pin_number=>400705 )
   Pincode.create(:name =>"Nerul", :pin_number=>400706 )
   Pincode.create(:name =>"Airoli", :pin_number=>400708 )
   Pincode.create(:name =>"KK", :pin_number=>400709 )
   Pincode.create(:name =>"KK", :pin_number=>400710 )
   Pincode.create(:name =>"Bhayandar(w)", :pin_number=>401101 )
   Pincode.create(:name =>"Umparpada", :pin_number=>401102 )
   Pincode.create(:name =>"Dahanu(w)", :pin_number=>401103 )
   Pincode.create(:name =>"Mira Road(e)", :pin_number=>401104 )   
   Pincode.create(:name =>"Bhayandar(e)", :pin_number=>401105 )
   Pincode.create(:name =>"Bhayandar(w)", :pin_number=>401106 )
   Pincode.create(:name =>"Mira Road(e)", :pin_number=>401107 )
   Pincode.create(:name =>"Vasai(w)", :pin_number=>401201 )
   Pincode.create(:name =>"Vasai(w)", :pin_number=>401202 )
   Pincode.create(:name =>"Nalasopara(w)", :pin_number=>401203 )
   Pincode.create(:name =>"Virar(e)", :pin_number=>401204 )
   Pincode.create(:name =>"Vasai(e)", :pin_number=>401205 )
   Pincode.create(:name =>"Virar(e)", :pin_number=>401206 )
   Pincode.create(:name =>"Vasai(w)", :pin_number=>401207 )
   Pincode.create(:name =>"Vasai(e)", :pin_number=>401208 )
   Pincode.create(:name =>"NalaSopara(e)", :pin_number=>401209 )
   Pincode.create(:name =>"Vasai(e)", :pin_number=>401210 )

   Pincode.create(:name =>"Virar(w)", :pin_number=>401301 )
   Pincode.create(:name =>"Virar(w)", :pin_number=>401302 )
   Pincode.create(:name =>"Virar(e)", :pin_number=>401303 )

   Pincode.create(:name =>"Vasai(w)", :pin_number=>401304 )

   Pincode.create(:name =>"Palghar(e)", :pin_number=>401404 )
   Pincode.create(:name =>"Palghar(w)", :pin_number=>401501 )
   Pincode.create(:name =>"Palghar(w)", :pin_number=>401502 )
   Pincode.create(:name =>"Dahanu(w)", :pin_number=>401503 )
   Pincode.create(:name =>"Palghar(w)", :pin_number=>401504 )
   Pincode.create(:name =>"Palghar(w)", :pin_number=>401506 )

   Pincode.create(:name =>"Dahanu(e)", :pin_number=>401601 )
   Pincode.create(:name =>"Dahanu(e)", :pin_number=>401602 )
   Pincode.create(:name =>"Dahanu(e)", :pin_number=>401606 )
   Pincode.create(:name =>"Dahanu", :pin_number=>401608 )
   Pincode.create(:name =>"Dahanu(w)", :pin_number=>401701 )

   Pincode.create(:name =>"Panvel", :pin_number=>410206 )
   Pincode.create(:name =>"Panvel", :pin_number=>410208 )
   Pincode.create(:name =>"Kamothe", :pin_number=>410209 )
   Pincode.create(:name =>"Kharghar", :pin_number=>410210 )
   Pincode.create(:name =>"Kalamboli", :pin_number=>410218 )

   Pincode.create(:name =>"Ulhasnagar", :pin_number=>421001 )
   Pincode.create(:name =>"Ulhasnagar", :pin_number=>421002 )
   Pincode.create(:name =>"Ulhasnagar", :pin_number=>421003 )
   Pincode.create(:name =>"Ulhasnagar", :pin_number=>421004 )
   Pincode.create(:name =>"Ulhasnagar", :pin_number=>421005 )

   Pincode.create(:name =>"Ambivali", :pin_number=>421102 )

   Pincode.create(:name =>"Dombivali", :pin_number=>421201 )
   Pincode.create(:name =>"Dombivali", :pin_number=>421202 )
   Pincode.create(:name =>"Dombivali", :pin_number=>421203 )
   Pincode.create(:name =>"Dombivali", :pin_number=>421204 )

   Pincode.create(:name =>"Kalyan", :pin_number=>421301 )
   Pincode.create(:name =>"Bhiwandi", :pin_number=>421302 )
   Pincode.create(:name =>"Wada", :pin_number=>421303 )
   Pincode.create(:name =>"Kalyan", :pin_number=>421304 )
   Pincode.create(:name =>"Bhiwandi", :pin_number=>421305 )
   Pincode.create(:name =>"Kalyan", :pin_number=>421306 )

   Pincode.create(:name =>"Ambernath", :pin_number=>421501 )
   Pincode.create(:name =>"Ambernath", :pin_number=>421502 )
   Pincode.create(:name =>"Ambernath", :pin_number=>421503 )
   Pincode.create(:name =>"Ambernath", :pin_number=>421505 )
   Pincode.create(:name =>"Badlapur", :pin_number=>421506 )
